/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vr8kLLfKD5l
 */
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div className="w-full max-w-2xl mx-auto p-4 md:p-6 lg:p-8">
      <h1 className="text-2xl font-bold text-center mb-6">AI Image Generation</h1>
      <div className="grid gap-6">
        <div className="border-2 border-dashed rounded-md p-6 text-center">
          <p className="mb-2 text-gray-500">Drag and drop your image here</p>
          <Input className="hidden" id="image-upload" type="file" />
          <Label className="cursor-pointer text-blue-600 underline" htmlFor="image-upload">
            Or click to upload
          </Label>
        </div>
        <div className="grid gap-4">
          <div className="grid gap-1.5">
            <Label htmlFor="prompt">Prompt</Label>
            <Input id="prompt" placeholder="Enter your prompt" />
          </div>
          <div className="grid gap-1.5">
            <Label htmlFor="negative-prompt">Negative Prompt</Label>
            <Input id="negative-prompt" placeholder="Enter your negative prompt" />
          </div>
          <div className="grid gap-1.5">
            <Label htmlFor="images-count">Number of Images</Label>
            <Input defaultValue="1" id="images-count" max="4" min="1" type="number" />
          </div>
          <div className="grid gap-1.5">
            <Label htmlFor="inference-steps">Inference Steps</Label>
            <Input defaultValue="1" id="inference-steps" min="1" type="number" />
          </div>
          <div className="grid gap-1.5">
            <Label htmlFor="merge-step">Merge Step</Label>
            <Input defaultValue="1" id="merge-step" min="1" type="number" />
          </div>
        </div>
        <Button className="w-full">Generate Images</Button>
      </div>
    </div>)
  );
}
